name: ibanking
description: ibanking

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: 3.27.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  logger: ^2.4.0
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.12
  flutter_animate: ^4.5.0
  connectivity_plus: ^6.1.0
  flutter_inappwebview: ^6.1.5
  r_dotted_line_border: ^0.1.1
  carousel_slider: ^5.0.0
  loading_animation_widget: ^1.3.0
  iconsax: ^0.0.8
  flip_card: ^0.7.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  dropdown_button2: ^2.3.9
  restart_app: ^1.3.2
  custom_date_range_picker: ^1.1.0
  path_provider: ^2.1.4
  open_file: ^3.5.8
  dio: ^5.7.0
  dynamic_languages:
    git:
      url: https://github.com/appdevsx/dynamic_languages
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: any
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  rename_app: ^1.6.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/appLauncher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
